# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorConfigurationProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('min_processing_time', models.DurationField()),
                ('max_processing_time', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='max_processing_time',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='min_processing_time',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='vendorconfigurationprocess',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_calculator.Configuration'),
        ),
        migrations.AddField(
            model_name='vendorconfigurationprocess',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_calculator.Vendor'),
        ),
    ]
