# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_calculator', '0002_auto_20160604_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorconfigurationprocess',
            name='max_processing_time',
        ),
        migrations.RemoveField(
            model_name='vendorconfigurationprocess',
            name='min_processing_time',
        ),
        migrations.AddField(
            model_name='vendorconfigurationprocess',
            name='max_processing_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vendorconfigurationprocess',
            name='min_processing_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
