# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_calculator', '0004_auto_20160607_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
