# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_calculator', '0005_auto_20160608_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendors',
        ),
    ]
