# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_calculator', '0006_remove_product_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='name',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
